name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.idea/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - run: ./kotlin build
      - run: ./kotlin check
